### ISSUE TITLE
Is support for Croatian eID cards released?

### ISSUE THREAD

**Issue by StipoR** [web-eid/libelectronic-id#22]
Hi!

The website https://web-eid.eu/ says that Croatian eID cards are supported in the first phase, but when I try to sign using the code from https://github.com/web-eid/web-eid-spring-boot-example with my Croatian eID card I get the following window:
<img width="275" alt="CardNotSupported" src="https://user-images.githubusercontent.com/63283166/137958231-0eed937b-a594-4a43-bc99-d57a59980a8f.png">

The web-eid.log in the C:\Users\[User]\AppData\Local\RIA\web-eid has the following lines:

> 2021-10-19T16:59:58.051Z INFO src\controller\controller.cpp:76:void __cdecl Controller::run(void) - "web-eid" app "1.0.0+527" running in stdin/stdout mode
2021-10-19T16:59:58.572Z DEBUG src\controller\threads\controllerchildthread.hpp:105:void __cdecl ControllerChildThread::beforeRun(void) - Starting "WaitForCardThread" 1849941933440 for command "INSERT_CARD"
2021-10-19T17:00:48.653Z DEBUG src\controller\controller.cpp:319:void __cdecl Controller::onDialogCancel(void) - User cancelled
2021-10-19T17:00:48.660Z DEBUG src\controller\controller.cpp:63:void __cdecl `anonymous-namespace'::interruptThread(class QThread *) - Interrupting thread 1849941933440
2021-10-19T17:00:48.663Z INFO src\controller\threads\controllerchildthread.hpp:47:void __cdecl ControllerChildThread::run(void) - "WaitForCardThread" 1849941933440 for command "INSERT_CARD" completed successfully
2021-10-19T17:00:48.664Z DEBUG src\controller\controller.cpp:148:auto __cdecl Controller::saveChildThreadPtrAndConnectFailureFinish::<lambda_3e97e70140d2e0a9c6ad97d32f838a34>::operator ()(void) const - Thread 1849941933440 finished
2021-10-19T17:00:48.664Z DEBUG src\controller\threads\controllerchildthread.hpp:96:__cdecl ControllerChildThread::~ControllerChildThread(void) - "WaitForCardThread" 1849941933440 destroyed

Is support for Croatian eID cards released because it doesn't work for my Croatian eID card and because I see that https://github.com/web-eid/libelectronic-id/pull/2 pull request is still open?

**Comment by mrts** [comment]
@StipoR, support for Croatian eID cards will be included in the next 2.1.0 release. Release candidate will be ready next week hopefully and the release will be out after a period of testing.

**Comment by StipoR** [comment]
> @StipoR, support for Croatian eID cards will be included in the next 2.1.0 release. Release candidate will be ready next week hopefully and the release will be out after a period of testing.

Thanks for the info, Mart!

**Comment by mrts** [comment]
@StipoR, we refactored the PKCS#11 layer which may affect the Croatian eID cards. Can you please test that the latest build from https://github.com/web-eid/web-eid-app main branch works without issues?

**Comment by StipoR** [comment]
@mrts I didn't work with web-eid for quite some time now.
I uninstalled the previous version of web-eid and installed the latest one for Windows as explained in https://web-eid.eu/#usage

Then I tried to test the Authentication with the button on that page but it failed with the following error:

> Authentication failed
> 
> [Code]
> 403
> 
> [Message]
> Server error: {"timestamp":"2023-06-12T09:24:35.672+00:00","status":403,"error":"Forbidden","message":"Forbidden","path":"/auth/login"}

Let me know if there is some other location from where to download the installer for the latest build from https://github.com/web-eid/web-eid-app main branch and if there is some other functional demo site for signing/authentication.

Regards,
Stipo

**Comment by mrts** [comment]
You can download the latest build from here: https://github.com/web-eid/web-eid-app/actions/runs/5542410823 -> _Artifacts_: https://github.com/web-eid/web-eid-app/suites/14271265041/artifacts/802003573.

My colleague @kinomehaanik will give testing instructions.

**Comment by StipoR** [comment]
Sorry for such a late response.

I just want to confirm that Croatian eID cards work as expected.

I tested it with the latest [web-eid-app artifacts](https://github.com/web-eid/web-eid-app/actions/runs/6890789428) (Version: 2.5.0+1712) and the latest [web-eid.js release](https://github.com/web-eid/web-eid.js/releases) (v2.0.2).

For testing, I used the ASP.NET application that I wrote (mentioned [here](https://github.com/web-eid/web-eid-asp-dotnet-example/issues/2#issuecomment-970204236)). I just had to refactor it [from Version 1 to Version 2 of web-eid.js](https://github.com/web-eid/web-eid.js#upgrading-from-version-1-to-version-2).

Using my test application I managed to successfully create a signed PDF file.

Sorry again for such a delayed response and keep up the good work!

**Comment by mrts** [comment]
Thanks a lot for testing! No problem with the delay, we understand that everyone has other priorities.
