### ISSUE TITLE
Belgian eID card support

### ISSUE THREAD

**Issue by matsjoonas** [web-eid/libelectronic-id#30]
Hi!

First of all, huge thanks for this project! Makes eID card integrations so much easier.

We have many clients who'd like to use their Belgian eID cards with web-eid extension, so, what are your plans regarding adding Belgian eID?

I could also provide a Belgian eID test card for you if necessary.

**Comment by mrts** [comment]
Hello, Mats-Joonas!

Thank you for the good words! We are definitely interested in adding Belgian eID support in the next release. We are currently preparing the v2.1.0 release, let's discuss how to make it happen once v2.1.0 is out.

**Comment by mrts** [comment]
Support for generation v1.7 cards is now added, waiting for generation v1.8 support.

Thank you @matsjoonas for your good work!

**Comment by mrts** [comment]
Belgian eID support was merged into main: https://github.com/web-eid/web-eid-app/pull/213. Wish you good luck with your Belgian users!
