### ISSUE TITLE
Available certificates p12

### ISSUE THREAD

**Issue by fabrii** [web-eid/libelectronic-id#35]
Hi! I would like to know if it is possible to make signatures with self-contained p12 certificates that are outside of a smart card. 

Thank you!

**Comment by fabrii** [comment]
Moved the issue to web-eid

**Comment by fabrii** [comment]
Hi @mrts. In this moment I am researching about the library for a specific project, where the supported signature types are not yet defined.

In other projects I have worked, sometimes the users do not have access to smart cards. An option is to implement a custom CA, for example with EJBCA (https://www.ejbca.org/). In that case, the users have access to their p12 certificates as a file protected with password.

**Comment by mrts** [comment]
This will be much easier, at least in Windows, when https://github.com/web-eid/libelectronic-id/pull/36 is merged. This PR brings tier 3 support for Windows CryptoAPI tokens to Web eID. We will officially support only hardware tokens, but you could experiment with software tokens easily by removing [the following line](https://github.com/web-eid/libelectronic-id/pull/36/files#diff-bb9f0e4249a0791dcd8dba53f181aa3ab6007f982785da8afe53d73a311a4786R164) that filters out software tokens:

```diff
-        if ((type & (NCRYPT_IMPL_HARDWARE_FLAG | NCRYPT_IMPL_REMOVABLE_FLAG)) == 0) {
-            continue;
-        }
```

We can later consider making software token support configurable with an environment variable, but we have to discuss this with the project owner and we need confirmation first that this would actually be useful for you (and information how many users there will be etc), so we expect that you build and experiment with the solution on your own. Are you willing to do this?

**Comment by mrts** [comment]
Alright, a fair decision! Please get in touch if we can support you further in any way.
