### ISSUE TITLE
Support for Halcom eID

### ISSUE THREAD

**Issue by archerixx** [web-eid/libelectronic-id#87]
Hi, 

I am reaching out to inquire about the possibility of adding support for the Halcom eID (https://www.halcom.com/). Currently, our country (Bosnia and Herzegovina) supports Halcom eID and I am interested in implementing digital sign for it.

Could you point me to relevant documentation or information on how I might implement this, or if possible, assist me directly in adding support for Halcom eID in your system?

Thank you

**Comment by kristelmerilain** [comment]
Hi!

You can find the guide on how to add support for new electronic IDs from [here](https://github.com/web-eid/libelectronic-id/wiki/how-to-add-support-for-new-electronic-ids).
